#!/bin/bash
set -eou pipefail

BASEDIR=/mnt/bleh/albums/
MINDEPTH=3

id=$1
v=`find $BASEDIR -mindepth $MINDEPTH  -type d   | sort | awk ' BEGIN { FS="/" } { print NR "/" $5 "/" $6 "/" $7 } ' | grep "^$id/" || true`
if [ -z "$v" ];  then
	echo wut
	exit 1
fi

dccpath=`pwd`/dcc
if [ ! -e "$dccpath" ]; then
	echo no dcc path
	exit 1
fi
zpath="$dccpath/$id.zip"
if [ ! -e "$zpath" ]; then
	dpath=$BASEDIR/$(echo "$v" | cut -f2- -d/)
	dpath1=$(echo "$dpath" | cut -f1-6 -d/)
	pushd "$dpath1" >/dev/null
	dpath2=$(echo "$dpath" | cut -f7,8 -d/)
	zip "$zpath" -r "$dpath2"/ >/dev/null
	popd >/dev/null
fi

sz=`stat -c"%s" $zpath`
ip=1
pasvid=123
port=0
echo -en "\x01DCC SEND $id.zip $ip $port $sz $pasvid\x01"
