#!/bin/bash
set -eox pipefail
outpage=`curl -L --max-time 2 "$1"`
s=`echo "$outpage" | grep -a -oP '<title>\K([^<]+)'`
if [ -n "$s" ]; then
	python3 -c "import html, sys; print(html.unescape(sys.argv[1]))" "$s"
fi
